### ISSUE TITLE
Feedbacks Milestione 4

### ISSUE THREAD

**Issue by sirine-chahma** [hadleyd2/group_09-1#8]
Great job! You implemented most of the feedbacks you received in an efficient way! 
The sketch of your dashboard is great, and your dashboard is going to be effective, and it is totally doable! 
Great description of your dashboard usage! 
I'm really excited to see your dashobard!

**Comment by hadleyd2** [comment]
Hello @sirine-chahma,

Thanks so much for the feedback and the kind words!

Since there are no action items in your feedback, I am closing the issue.

-Dan
