### ISSUE TITLE
Feedbacks milestone 5

### ISSUE THREAD

**Issue by sirine-chahma** [hadleyd2/group_09-1#9]
Great job! Here are a few things that I would change : 

- The components that you use to filter your data in the `Data Analysis` part are overlapping, try to introduce a blank element between your components. 
- Try to replace the 'Independant variable' by the name of the variable selected by the user in the 'Apply Transform to Independent Variable' text.
- When the user select `Minimum stay` in the `Data Exploration` part, don't rotate the values of the x-axis. 
- Try to keep the same format for your y-axis (the plot on the right has the euro sign next to each values while the one on the left has the euro sign on the axis title) : I personally prefer having the euro sign next to the title of the axis
- I would add the 'Minimum stay' variable in the independant variables that you can use for the linear regression.
- Increase the size of the plots for the `Data Exploration` part (the size of the plot when the x-axis is `Minimum stay` is good, try to do the same for the other variables).
- Keep the same size for the titles of the axis of your plots (I think they are bigger in the `Data Exploration` plots than in the `Data Analysis` part).

All those comments are minor changes, you did a very good job!

**Comment by hadleyd2** [comment]
Hello @sirine-chahma,

Thanks so much for the feedback and kind words! My response to each comment of your feedback follows in *italics*:

- The components that you use to filter your data in the `Data Analysis` part are overlapping, try to introduce a blank element between your components. 
    - *I assume the components you are referring to are the sliders, but I was not able to replicate any overlapping. I tried in Chrome and Safari with resizing the browser window. The sliders were always properly spaced. I noticed that the labels on the sliders start to overlap if you shrink the window horizontally. Is this what you are referring to? If you can give me your steps to replicate, I'll be happy to try and reproduce on my end. To attempt to blindly fix this issue, I added margins around each slider component. I've created a separate issue [here](https://github.com/hadleyd2/group_09-1/issues/10) for us to track this fix.*

- Try to replace the 'Independant variable' by the name of the variable selected by the user in the 'Apply Transform to Independent Variable' text.
    - *Great tip! This is now done using a Markdown component.*

- When the user select `Minimum stay` in the `Data Exploration` part, don't rotate the values of the x-axis. 
    - *Another nice catch! This is done with a logical.*

- Try to keep the same format for your y-axis (the plot on the right has the euro sign next to each values while the one on the left has the euro sign on the axis title) : I personally prefer having the euro sign next to the title of the axis
    - *Thanks for this. I changed the format so that it is consistent with the Euro sign appearing next to the axis title.*

- I would add the 'Minimum stay' variable in the independent variables that you can use for the linear regression.
    - *Done. This was originally omitted so that users could not filter the data down to one minimum stay option rendering the scatterplot redundant (since it is basically a density plot) and the trendline as an arithmetic average. To try and mitigate this, I added logicals so that if minimum stay is the independent variable and minimum stay is filtered down to one day, then a jitter plot is produced with a horizontal line for the mean price. If minimum stay is the independent variable but there are multiple values within the filter range, then a jitter plot with a trendline is produced.*

- Increase the size of the plots for the `Data Exploration` part (the size of the plot when the x-axis is `Minimum stay` is good, try to do the same for the other variables).
    - *I am not sure how to do this using layouts. Once I give an `htmlDiv()` a portion of the screen's real estate, isn't the plot always forced into that area? If that's the case, then the solution that first comes to my mind is to resize that portion of the screen used by the `htmlDiv()`. In that case, the Data Analysis section is going to get squeezed or shifted each time the plot on the left is resized. From a user's perspective, I would hate if all of the contents on the screen shifted each time I used a drop down. I think my proposed solution to this problem would be to break the Data Exploration and Data Analysis portions into tabs. Then, I can dynamically resize the plot. Again thinking as a user, I wouldn't like if the plot resized just because there are more groups on the x-axis. If I throw more into a plot, I would simply expect the plot to be more crowded, not create a bigger plot. Adding this as future work [here](https://github.com/hadleyd2/group_09-1/issues/11).*

- Keep the same size for the titles of the axis of your plots (I think they are bigger in the `Data Exploration` plots than in the `Data Analysis` part).
    - *Thanks for pointing this out! Plot labels should now be consistent between the Exploration and Analysis portions of the dashboard.*
